export const Area = () => <></>
export const AreaChart = () => <></>
export const Bar = () => <></>
export const BarChart = () => <></>
export const CartesianGrid = () => <></>
export const Legend = () => <></>
export const ResponsiveContainer = () => <></>
export const Tooltip = () => <></>
export const XAxis = () => <></>
export const YAxis = () => <></>
